if("undefined"===typeof imageInstant)var imageInstant=function(){var h={enabled:!0},f=[],g=function(b,a,c){b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent?b.attachEvent("on"+a,c):b.setAttribute("on"+a,c)},k=function(b){for(var a=f.length-1;0<=a;a--)if(f[a].img.isEqualNode(b))return f[a].toolbar;return null},i=function(){var b=window.event?window.event.srcElement:this,a=b.parentNode,c=k(b);if(null===c){var d=document.createElement("div");d.style.position="relative";var e=b.cloneNode(!0);
g(e,"mouseover",i);g(e,"mouseout",j);d.appendChild(e);a.replaceChild(d,b);c=l(e);f.push({img:e,toolbar:c});d.appendChild(c)}else c.style.opacity="0.8"},j=function(){var b=k(window.event?window.event.srcElement:this);if(null!==b)b.style.opacity=0};h.initialize=function(){if(h.enabled){for(var b=document.getElementsByTagName("img"),a=b.length-1;0<=a;a--)try{var c=new Image;c.src=b[a].src;100<=c.width&&100<=c.height&&(g(b[a],"mouseover",i),g(b[a],"mouseout",j))}catch(d){alert(d)}alert("imageInstant is ready.")}else{b=
document.getElementsByTagName("img");for(a=b.length-1;0<=a;a--)b[a].removeEventListener("mouseover",i,!1),b[a].removeEventListener("mouseout",j,!1);for(a=f.length-1;0<=a;a--)b=f[a].img.parentNode,b.parentNode.replaceChild(f[a].img,b);f.splice(0,f.length);alert("imageInstant is unloaded.")}};var l=function(b){var a=document.createElement("ul");a.className="imageInstant";a.style.position="absolute";a.style.padding="0px";a.style.marginTop=(window.getComputedStyle?window.getComputedStyle(b):b.currentStyle?
b.currentStyle:null).marginTop;a.style.marginLeft=(window.getComputedStyle?window.getComputedStyle(b):b.currentStyle?b.currentStyle:null).marginLeft;a.style.top="0px";a.style.left="0px";a.style.backgroundColor="black";a.style.listStyleType="none";a.style.opacity="0.8";a.onmouseover=function(){a.style.opacity="0.8"};a.onmouseout=function(){a.style.opacity=0};for(engine in e){var c=document.createElement("li");c.style.display="block";c.style.margin="0px";c.style.padding="0px";var d=document.createElement("a");
d.style.color="white";d.style.textDecoration="none";d.style.margin="5px";d.href="javascript:void(0); ";d.innerHTML=engine;d.onclick=function(a,b){return function(){b(a)}}(b.src,e[engine]);c.appendChild(d);a.appendChild(c)}return a},e=[];e.iqdb=function(b){var a=document.createElement("form");a.action="http://iqdb.org/";a.method="post";a.enctype="multipart/form-data";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);document.body.appendChild(a);
a.submit()};e.sauceNAO=function(b){var a=document.createElement("form");a.action="http://saucenao.com/search.php";a.method="post";a.enctype="multipart/form-data";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);b=document.createElement("input");b.type="hidden";b.name="urlify";b.value="true";a.appendChild(b);document.body.appendChild(a);a.submit()};e.Google=function(b){var a=document.createElement("form");a.action="http://www.google.com/searchbyimage";
a.method="GET";a.enctype="multipart/form-data";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="image_url";c.value=b;a.appendChild(c);document.body.appendChild(a);a.submit()};e.TinEye=function(b){var a=document.createElement("form");a.action="http://www.tineye.com/search";a.method="POST";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);document.body.appendChild(a);a.submit()};e.Baidu=function(b){var a=document.createElement("form");
a.action="http://stu.baidu.com/i?";a.method="get";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="objurl";c.value=b;a.appendChild(c);b=document.createElement("input");b.type="hidden";b.name="rt";b.value="0";a.appendChild(b);b=document.createElement("input");b.type="hidden";b.name="rn";b.value="10";a.appendChild(b);b=document.createElement("input");b.type="hidden";b.name="ct";b.value="1";a.appendChild(b);b=document.createElement("input");b.type="hidden";b.name="tn";
b.value="baiduimage";a.appendChild(b);document.body.appendChild(a);a.submit()};return h}();else imageInstant.enabled=!imageInstant.enabled;imageInstant.initialize();
