if(null!=divInstant){for(var i=0;i<divInstant.length;i++){var divImg=divInstant[i],img=divImg.childNodes[0];img.removeEventListener("mouseover",showToolbar,!1);img.removeEventListener("mouseout",hideToolbar,!1);divImg.parentNode.appendChild(divImg.removeChild(img));divImg.parentNode.removeChild(divImg)}divInstant=null;alert("imageInstant is unloaded.")}else{for(var divInstant=[],showToolbar=function(){for(var b=this.parentNode.lastChild;1!=b.nodeType;)b=b.previousSibling;b.style.opacity="0.8"},hideToolbar=
function(){for(var b=this.parentNode.lastChild;1!=b.nodeType;)b=b.previousSibling;b.style.opacity="0"},imgs=document.getElementsByTagName("img"),i=0;i<imgs.length;i++)try{img=new Image,img.src=imgs[i].src,100<=img.width&&100<=img.height&&createToolbar(imgs[i])}catch(err){alert(err)}alert("imageInstant is ready.")}
function createToolbar(b){var a=b.parentNode,c=b.src,d=divInstant.length,e=document.createElement("div");e.style.position="relative";a.appendChild(e);e.appendChild(a.removeChild(b));a=document.createElement("ul");a.setAttribute("style","margin: 0px;padding: 0px;position: absolute;top: 0px;left: 0px;background-color: black;opacity: 0;list-style-type: none;");a.appendChild(createSearchEngine("iqdb","iqdbSearch('"+c+"');",d));a.appendChild(createSearchEngine("sauceNAO","sauceNAOSearch('"+c+"');",d));
a.appendChild(createSearchEngine("Google","googleSearch('"+c+"');",d));a.appendChild(createSearchEngine("TinEye","tineyeSearch('"+c+"');",d));a.appendChild(createSearchEngine("Baidu","baiduSearch('"+c+"');",d));e.appendChild(a);divInstant.push(e);b.addEventListener?b.addEventListener("mouseover",showToolbar,!1):b.attachEvent&&b.attachEvent("onclick",showToolbar);b.addEventListener?b.addEventListener("mouseout",hideToolbar,!1):b.attachEvent&&b.attachEvent("onmouseout",hideToolbar);a.setAttribute("onmouseover",
"this.style.opacity=0.8;");a.setAttribute("onmouseout","this.style.opacity=0;")}function createSearchEngine(b,a){var c=document.createElement("li");c.setAttribute("style","display: block;margin: 0px;padding: 0px;");var d=document.createElement("a");d.setAttribute("style","color: white;text-decoration: none;margin: 5px;");d.href="javascript:void(0);";d.setAttribute("onclick",a);d.innerHTML=b;c.appendChild(d);return c}
function iqdbSearch(b){var a=document.createElement("form");a.action="http://iqdb.org/";a.method="post";a.enctype="multipart/form-data";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);document.body.appendChild(a);a.submit()}
function sauceNAOSearch(b){var a=document.createElement("form");a.action="http://saucenao.com/search.php";a.method="post";a.enctype="multipart/form-data";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);b=document.createElement("input");b.type="hidden";b.name="urlify";b.value="true";a.appendChild(b);document.body.appendChild(a);a.submit()}
function googleSearch(b){var a=document.createElement("form");a.action="http://www.google.com/searchbyimage";a.method="GET";a.enctype="multipart/form-data";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="image_url";c.value=b;a.appendChild(c);document.body.appendChild(a);a.submit()}
function tineyeSearch(b){var a=document.createElement("form");a.action="http://www.tineye.com/search";a.method="POST";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);document.body.appendChild(a);a.submit()}
function sakuraSearch(b){var a=document.createElement("form");a.action="http://www.tineye.com/search";a.method="POST";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="url";c.value=b;a.appendChild(c);document.body.appendChild(a);a.submit()}
function baiduSearch(b){var a=document.createElement("form");a.action="http://stu.baidu.com/i?";a.method="get";a.target="_blank";var c=document.createElement("input");c.type="hidden";c.name="objurl";c.value=b;a.appendChild(c);b=document.createElement("input");b.type="hidden";b.name="rt";b.value="0";a.appendChild(b);b=document.createElement("input");b.type="hidden";b.name="rn";b.value="10";a.appendChild(b);b=document.createElement("input");b.type="hidden";b.name="ct";b.value="1";a.appendChild(b);b=
document.createElement("input");b.type="hidden";b.name="tn";b.value="baiduimage";a.appendChild(b);document.body.appendChild(a);a.submit()};
